import {SlashCommandBuilder,ChatInputCommandInteraction,PermissionFlagsBits,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ChannelType} from 'discord.js';
import {db,guilds,warnings,balances,cases,xp,economyItems} from '@dynex/database'; import {and,eq,desc} from 'drizzle-orm'; import {nanoid} from 'nanoid';
import {warn,caseHistory,applyModeration} from '../services/moderation.js'; import {assertMemberAction} from '../services/permissions.js'; import {askAI} from '../services/ai.js'; import {cooldown,ensureGuild,setConfig,getConfig,recordAudit,transaction} from '../services/store.js'; import {play,control} from '../services/music.js'; import {createTicket} from '../services/tickets.js'; import {createPoll,createSuggestion,createEvent} from '../services/community.js'; import {createBackup} from '../services/backup.js'; import {translate} from '../services/translation.js'; import {syncNativeAutoMod} from '../services/automod.js'; import {leaderboard} from '../services/leveling.js'; import {createGiveaway,reroll} from '../services/giveaways.js'; import {sendRolePanel} from '../services/roles.js'; import {db as database,securityTrusted} from '@dynex/database';
export const commands=[
new SlashCommandBuilder().setName('help').setDescription('Interactive DYNEX help center'),new SlashCommandBuilder().setName('setup').setDescription('Interactive DYNEX setup center').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString()),
new SlashCommandBuilder().setName('warn').setDescription('Warn a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers.toString()),
new SlashCommandBuilder().setName('warnings').setDescription('Warning/case history').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers.toString()),
new SlashCommandBuilder().setName('timeout').setDescription('Timeout a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Minutes').setMinValue(1).setMaxValue(40320).setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')) .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers.toString()),
new SlashCommandBuilder().setName('kick').setDescription('Kick a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')).setDefaultMemberPermissions(PermissionFlagsBits.KickMembers.toString()),
new SlashCommandBuilder().setName('ban').setDescription('Ban a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')).setDefaultMemberPermissions(PermissionFlagsBits.BanMembers.toString()),
new SlashCommandBuilder().setName('unban').setDescription('Unban a user').addStringOption(o=>o.setName('user_id').setDescription('User ID').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.BanMembers.toString()),
new SlashCommandBuilder().setName('purge').setDescription('Delete messages').addIntegerOption(o=>o.setName('amount').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages.toString()),
new SlashCommandBuilder().setName('slowmode').setDescription('Set channel slowmode').addIntegerOption(o=>o.setName('seconds').setDescription('0-21600').setMinValue(0).setMaxValue(21600).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels.toString()),
new SlashCommandBuilder().setName('lockdown').setDescription('Lock all text channels').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString()),
new SlashCommandBuilder().setName('automod-sync').setDescription('Sync DYNEX rules to Discord AutoMod').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString()),
new SlashCommandBuilder().setName('level').setDescription('View level').addUserOption(o=>o.setName('user').setDescription('Member')),new SlashCommandBuilder().setName('leaderboard').setDescription('Level leaderboard'),
new SlashCommandBuilder().setName('balance').setDescription('View balance').addUserOption(o=>o.setName('user').setDescription('Member')),new SlashCommandBuilder().setName('daily').setDescription('Daily reward'),new SlashCommandBuilder().setName('work').setDescription('Work reward'),
new SlashCommandBuilder().setName('shop').setDescription('List shop items'),new SlashCommandBuilder().setName('buy').setDescription('Buy an item').addStringOption(o=>o.setName('item_id').setDescription('Item ID').setRequired(true)),
new SlashCommandBuilder().setName('ai').setDescription('AI chat').addStringOption(o=>o.setName('prompt').setDescription('Prompt').setRequired(true)),new SlashCommandBuilder().setName('teacher').setDescription('AI teacher mode').addStringOption(o=>o.setName('topic').setDescription('Topic').setRequired(true)),
new SlashCommandBuilder().setName('play').setDescription('Play direct media URL').addStringOption(o=>o.setName('url').setDescription('HTTP(S) media URL').setRequired(true)),new SlashCommandBuilder().setName('music').setDescription('Control music').addStringOption(o=>o.setName('action').setDescription('Action').setRequired(true).addChoices({name:'pause',value:'pause'},{name:'resume',value:'resume'},{name:'skip',value:'skip'},{name:'shuffle',value:'shuffle'},{name:'clear',value:'clear'},{name:'loop',value:'loop'})).addIntegerOption(o=>o.setName('volume').setDescription('0-200').setMinValue(0).setMaxValue(200)),
new SlashCommandBuilder().setName('ticket').setDescription('Create private ticket'),new SlashCommandBuilder().setName('poll').setDescription('Create poll').addStringOption(o=>o.setName('question').setDescription('Question').setRequired(true)).addStringOption(o=>o.setName('options').setDescription('A|B|C').setRequired(true)),new SlashCommandBuilder().setName('suggestion-action').setDescription('Approve, deny or respond to a suggestion').addStringOption(o=>o.setName('id').setDescription('Suggestion ID').setRequired(true)).addStringOption(o=>o.setName('status').setDescription('pending/approved/denied').setRequired(true)).addStringOption(o=>o.setName('response').setDescription('Staff response')).setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages.toString()),new SlashCommandBuilder().setName('suggest').setDescription('Submit suggestion').addStringOption(o=>o.setName('text').setDescription('Suggestion').setRequired(true)),
new SlashCommandBuilder().setName('event').setDescription('Create event').addStringOption(o=>o.setName('title').setDescription('Title').setRequired(true)).addStringOption(o=>o.setName('when').setDescription('ISO date/time').setRequired(true)).addStringOption(o=>o.setName('description').setDescription('Description')),new SlashCommandBuilder().setName('reroll').setDescription('Reroll a finished giveaway').addStringOption(o=>o.setName('id').setDescription('Giveaway ID').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString()),new SlashCommandBuilder().setName('rolepanel').setDescription('Create a persistent self-role panel').addStringOption(o=>o.setName('title').setDescription('Panel title').setRequired(true)).addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageRoles.toString()),new SlashCommandBuilder().setName('trust').setDescription('Trust or untrust a security user').addUserOption(o=>o.setName('user').setDescription('User')).addRoleOption(o=>o.setName('role').setDescription('Role')).addBooleanOption(o=>o.setName('enabled').setDescription('Trusted?').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString()),new SlashCommandBuilder().setName('giveaway').setDescription('Create giveaway').addStringOption(o=>o.setName('prize').setDescription('Prize').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Duration').setMinValue(1).setMaxValue(10080).setRequired(true)).addIntegerOption(o=>o.setName('winners').setDescription('Winner count').setMinValue(1).setMaxValue(20).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString()),
new SlashCommandBuilder().setName('translate').setDescription('Translate text').addStringOption(o=>o.setName('text').setDescription('Text').setRequired(true)).addStringOption(o=>o.setName('language').setDescription('Target language code').setRequired(true)),new SlashCommandBuilder().setName('backup').setDescription('Create supported Discord configuration backup').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString()),
new SlashCommandBuilder().setName('audit').setDescription('DYNEX audit log').setDefaultMemberPermissions(PermissionFlagsBits.ViewAuditLog.toString()),new SlashCommandBuilder().setName('serverinfo').setDescription('Server information')
].map(x=>x.toJSON());
const btn=(id:string,label:string,style=ButtonStyle.Secondary)=>new ButtonBuilder().setCustomId(id).setLabel(label).setStyle(style);
export async function handle(i:ChatInputCommandInteraction){if(!i.guild)return i.reply({content:'Use DYNEX in a server.',ephemeral:true});await ensureGuild(i.guild);try{switch(i.commandName){
case'help':return i.reply({embeds:[new EmbedBuilder().setTitle('DYNEX • Help Center').setDescription('Select a system to view its real commands and configuration areas.')],components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('help:system').setPlaceholder('Select a system').addOptions(['Moderation','Security','AutoMod','Tickets','Music','Leveling','Economy','Giveaways','Roles','Welcome','Temp Voice','Starboard','Polls','Suggestions','Analytics','Events','Backups','Translation','AI','Configuration'].map(x=>({label:x,value:x.toLowerCase().replace(/ /g,'_')}))))]});
case'setup':return i.reply({embeds:[new EmbedBuilder().setTitle('DYNEX • Setup Center').setDescription('Persistent server configuration. Dashboard settings use the same PostgreSQL records.')],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(btn('setup:security','Security'),btn('setup:automod','AutoMod'),btn('setup:welcome','Welcome'),btn('setup:ai','AI'),btn('setup:logs','Logs'))]});
case'warn':{const u=i.options.getUser('user',true),m=await i.guild.members.fetch(u.id);const id=await warn(i.guild.id,u.id,i.user.id,i.options.getString('reason',true));return i.reply(`⚠️ Warned <@${u.id}>. Case **${id}**`);}
case'warnings':{const u=i.options.getUser('user',true),rows=await caseHistory(i.guild.id,u.id);return i.reply({embeds:[new EmbedBuilder().setTitle(`Cases • ${u.tag}`).setDescription(rows.length?rows.slice(0,15).map(x=>`**${x.type}** ${x.id} — ${x.reason??'No reason'} — <t:${Math.floor(x.createdAt.getTime()/1000)}:R>`).join('\n'):'No cases found.')]});}
case'timeout':{const u=i.options.getUser('user',true),m=await i.guild.members.fetch(u.id),min=i.options.getInteger('minutes',true),reason=i.options.getString('reason')??'DYNEX moderation';const id=await applyModeration(i.client,m,i.member as any,'TIMEOUT',reason,()=>m.timeout(min*60000,reason));return i.reply(`⏱️ Timeout applied. Case **${id}**`);}
case'kick':{const u=i.options.getUser('user',true),m=await i.guild.members.fetch(u.id),reason=i.options.getString('reason')??'DYNEX moderation';const id=await applyModeration(i.client,m,i.member as any,'KICK',reason,()=>m.kick(reason));return i.reply(`👢 Kicked <@${u.id}>. Case **${id}**`);}
case'ban':{const u=i.options.getUser('user',true),m=await i.guild.members.fetch(u.id),reason=i.options.getString('reason')??'DYNEX moderation';const id=await applyModeration(i.client,m,i.member as any,'BAN',reason,()=>m.ban({reason}));return i.reply(`🔨 Banned <@${u.id}>. Case **${id}**`);}
case'unban':if(!(i.member as any).permissions.has(PermissionFlagsBits.BanMembers))throw new Error('You do not have Ban Members permission.');await i.guild.members.unban(i.options.getString('user_id',true),'DYNEX unban');return i.reply('✅ User unbanned.');
case'purge':{if(!(i.member as any).permissions.has(PermissionFlagsBits.ManageMessages))throw new Error('You do not have Manage Messages permission.');if(!i.channel?.isTextBased()||!('bulkDelete'in i.channel))throw new Error('Unsupported channel.');const n=i.options.getInteger('amount',true);const d=await (i.channel as any).bulkDelete(n,true);await recordAudit(i.guild.id,i.user.id,'moderation.purge',undefined,undefined,{count:d.size});return i.reply({content:`🧹 Deleted ${d.size} messages.`,ephemeral:true});}
case'slowmode':{if(!(i.member as any).permissions.has(PermissionFlagsBits.ManageChannels))throw new Error('You do not have Manage Channels permission.');if(!i.channel||!('setRateLimitPerUser'in i.channel))throw new Error('Unsupported channel.');await (i.channel as any).setRateLimitPerUser(i.options.getInteger('seconds',true),'DYNEX');return i.reply('🐢 Slowmode updated.');}
case'lockdown':{if(!(i.member as any).permissions.has(PermissionFlagsBits.ManageGuild))throw new Error('You do not have Manage Server permission.');for(const c of i.guild.channels.cache.values()){if(c.type===ChannelType.GuildText||c.type===ChannelType.GuildAnnouncement)await c.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:false},{reason:`DYNEX lockdown by ${i.user.tag}`}).catch(()=>null);}await recordAudit(i.guild.id,i.user.id,'security.lockdown');return i.reply('🔒 Emergency lockdown applied where permissions allow.');}
case'automod-sync':if(!(i.member as any).permissions.has(PermissionFlagsBits.ManageGuild))throw new Error('You do not have Manage Server permission.');await syncNativeAutoMod(i.guild);return i.reply('🛡️ Native Discord AutoMod synchronized.');
case'level':{const u=i.options.getUser('user')??i.user;const r=await db.select().from(xp).where(and(eq(xp.guildId,i.guild.id),eq(xp.userId,u.id))).limit(1);return i.reply(`📈 ${u.username}: Level **${r[0]?.level??1}**, XP **${r[0]?.xp??0}**, messages **${r[0]?.messages??0}**`);}
case'leaderboard':{const rows=await leaderboard(i.guild.id);return i.reply(rows.length?rows.map((x,n)=>`**${n+1}.** <@${x.userId}> — L${x.level} • ${x.xp} XP`).join('\n'):'No XP data yet.');}
case'balance':{const u=i.options.getUser('user')??i.user;const r=await db.select().from(balances).where(and(eq(balances.guildId,i.guild.id),eq(balances.userId,u.id))).limit(1);return i.reply(`💰 ${u.username}: **${r[0]?.balance??0}** credits.`);}
case'daily':{const r=await (await import('../services/economy.js')).reward(i.guild.id,i.user.id,'daily',250,'daily',86400);return i.reply(r.ok?`🎁 Daily: **${r.balance}** credits.`:`⏳ Try again in ${r.wait}s.`);}
case'work':{const amount=100+Math.floor(Math.random()*151);const r=await (await import('../services/economy.js')).reward(i.guild.id,i.user.id,'work',amount,'work',3600);return i.reply(r.ok?`💼 Work paid **${amount}** credits. Balance: **${r.balance}**.`:`⏳ Try again in ${r.wait}s.`);}
case'shop':{const rows=await db.select().from(economyItems).where(eq(economyItems.guildId,i.guild.id));return i.reply(rows.length?rows.map(x=>`**${x.id}** — ${x.name}: ${x.price} credits${x.stock>=0?` • stock ${x.stock}`:''}`).join('\n'):'Shop is empty. Add items through the dashboard/database configuration.');}
case'buy':{const item=i.options.getString('item_id',true);const r=await (await import('../services/economy.js')).buy(i.guild.id,i.user.id,item);return i.reply(`🛒 Purchase complete. Balance: **${r}**.`);}
case'ai':{await i.deferReply();return i.editReply(await askAI(i.options.getString('prompt',true),i.guild.id,i.channelId,i.user.id));}
case'teacher':{await i.deferReply();const topic=i.options.getString('topic',true);return i.editReply(await askAI(`Teach me about ${topic}. Use a student-friendly lesson, examples, a short practice question, and explain the answer after the student attempts it.`,i.guild.id,i.channelId,i.user.id));}
case'play':await i.deferReply();await play(i,i.options.getString('url',true));return i.editReply('▶️ Added to the server music queue.');
case'music':{const a=i.options.getString('action',true),v=i.options.getInteger('volume');control(i.guild.id,a,v??undefined);return i.reply(`🎵 ${a}${v!==null&&v!==undefined?` → ${v}%`:''}`);}
case'ticket':{const ch=await createTicket(i.guild,i.user);return i.reply({content:`🎫 ${ch}`,ephemeral:true});}
case'poll':{const opts=i.options.getString('options',true).split('|').map(x=>x.trim()).filter(Boolean).slice(0,5);if(opts.length<2)throw new Error('Provide at least 2 options separated by |.');await createPoll(i.channel,i.options.getString('question',true),opts);return i.reply({content:'Poll created.',ephemeral:true});}
case'suggestion-action':{const {suggestions}=await import('@dynex/database');const id=i.options.getString('id',true),status=i.options.getString('status',true);if(!['pending','approved','denied'].includes(status))throw new Error('Status must be pending, approved or denied.');await database.update(suggestions).set({status,staffResponse:i.options.getString('response')??null}).where(eq(suggestions.id,id));await recordAudit(i.guild.id,i.user.id,'suggestion.action',id,undefined,{status});return i.reply({content:`💡 Suggestion ${id} → ${status}.`,ephemeral:true});}
case'suggest':await createSuggestion(i.channel,i.user,i.options.getString('text',true));return i.reply({content:'💡 Suggestion submitted.',ephemeral:true});
case'event':{const d=new Date(i.options.getString('when',true));if(Number.isNaN(d.getTime()))throw new Error('Invalid ISO date/time.');await createEvent(i.channel,i.options.getString('title',true),d,i.options.getString('description')??'');return i.reply({content:'📅 Event created.',ephemeral:true});}
case'giveaway':await createGiveaway(i.channel,i.options.getString('prize',true),i.options.getInteger('winners',true),i.options.getInteger('minutes',true)*60000);return i.reply({content:'🎉 Giveaway created.',ephemeral:true});
case'translate':await i.deferReply();return i.editReply(await translate(i.guild.id,i.options.getString('text',true),i.options.getString('language',true)));
case'reroll':return i.reply(`🔄 Rerolled: <@${await reroll(i.client,i.options.getString('id',true))}>`);
case'rolepanel':{if(!(i.member as any).permissions.has(PermissionFlagsBits.ManageRoles))throw new Error('You do not have Manage Roles permission.');const r=i.options.getRole('role',true);if(r.position>=i.guild.members.me!.roles.highest.position)throw new Error('DYNEX cannot manage that role.');await sendRolePanel(i.channel,i.options.getString('title',true),[{id:r.id,label:r.name}],false);return i.reply({content:'🎭 Persistent role panel created.',ephemeral:true});}
case'trust':{const u=i.options.getUser('user');const r=i.options.getRole('role');if(!u&&!r)throw new Error('Provide a user or role.');const subjectId=u?.id??r!.id,kind=u?'user':'role',enabled=i.options.getBoolean('enabled',true);if(enabled)await database.insert(securityTrusted).values({guildId:i.guild.id,subjectId,kind}).onConflictDoNothing();else await database.delete(securityTrusted).where(and(eq(securityTrusted.guildId,i.guild.id),eq(securityTrusted.subjectId,subjectId),eq(securityTrusted.kind,kind)));return i.reply({content:`🛡️ ${enabled?'Trusted':'Untrusted'} ${u?u.tag:r!.name}.`,ephemeral:true});}
case'backup':{const b=await createBackup(i.guild,i.user.id);return i.reply({content:`💾 Backup **${b.id}** saved. It contains Discord-supported guild/channel/role configuration only; messages and bot secrets are not backed up.`,ephemeral:true});}
case'audit':{const rows=await db.select().from((await import('@dynex/database')).audit).where(eq((await import('@dynex/database')).audit.guildId,i.guild.id)).orderBy(desc((await import('@dynex/database')).audit.createdAt)).limit(15);return i.reply(rows.length?rows.map(x=>`${x.action} • <@${x.actorId}> • <t:${Math.floor(x.createdAt.getTime()/1000)}:R>`).join('\n'):'No DYNEX audit entries.');}
case'serverinfo':return i.reply(`**${i.guild.name}**\nMembers: ${i.guild.memberCount}\nChannels: ${i.guild.channels.cache.size}\nRoles: ${i.guild.roles.cache.size}`);
}}
catch(e){const msg=e instanceof Error?e.message:'Unexpected error';if(i.replied||i.deferred)await i.editReply(`❌ ${msg}`);else await i.reply({content:`❌ ${msg}`,ephemeral:true});}}
