import {db,guilds,config,cooldowns,audit,analytics,balances,economyTransactions} from '@dynex/database';
import {and,eq,gt} from 'drizzle-orm';
import {nanoid} from 'nanoid';
export async function ensureGuild(g:any){await db.insert(guilds).values({id:g.id,name:g.name,icon:g.iconURL?.()??null}).onConflictDoUpdate({target:guilds.id,set:{name:g.name,icon:g.iconURL?.()??null,updatedAt:new Date()}});}
export async function getConfig<T>(guildId:string,key:string, fallback:T):Promise<T>{const r=await db.select().from(config).where(and(eq(config.guildId,guildId),eq(config.key,key))).limit(1);return (r[0]?.value as T)??fallback;}
export async function setConfig(guildId:string,key:string,value:unknown){await db.insert(config).values({guildId,key,value,updatedAt:new Date()}).onConflictDoUpdate({target:[config.guildId,config.key],set:{value,updatedAt:new Date()}});}
export async function cooldown(guildId:string,userId:string,key:string,seconds:number){const now=new Date();const r=await db.select().from(cooldowns).where(and(eq(cooldowns.guildId,guildId),eq(cooldowns.userId,userId),eq(cooldowns.key,key),gt(cooldowns.expiresAt,now))).limit(1);if(r[0])return Math.ceil((r[0].expiresAt.getTime()-now.getTime())/1000);await db.insert(cooldowns).values({guildId,userId,key,expiresAt:new Date(now.getTime()+seconds*1000)}).onConflictDoUpdate({target:[cooldowns.guildId,cooldowns.userId,cooldowns.key],set:{expiresAt:new Date(now.getTime()+seconds*1000)}});return 0;}
export async function recordAudit(guildId:string,actorId:string,action:string,targetId?:string,before?:unknown,after?:unknown,metadata?:unknown){await db.insert(audit).values({id:nanoid(),guildId,actorId,action,targetId,before,after,metadata});}
export async function metric(guildId:string,type:string,userId?:string,channelId?:string,value=1,metadata?:unknown){await db.insert(analytics).values({id:nanoid(),guildId,type,userId,channelId,value,metadata});}
export async function transaction(guildId:string,userId:string,amount:number,type:string,metadata?:unknown){const r=await db.select().from(balances).where(and(eq(balances.guildId,guildId),eq(balances.userId,userId))).limit(1);const next=(r[0]?.balance??0)+amount;if(next<0)throw new Error('Insufficient balance.');if(r[0])await db.update(balances).set({balance:next,updatedAt:new Date()}).where(and(eq(balances.guildId,guildId),eq(balances.userId,userId)));else await db.insert(balances).values({guildId,userId,balance:next});await db.insert(economyTransactions).values({id:nanoid(),guildId,userId,amount,type,metadata});return next;}
