const play=require('play-dl');
const {joinVoiceChannel,createAudioPlayer,createAudioResource,AudioPlayerStatus,VoiceConnectionStatus}=require('@discordjs/voice');
const {db}=require('../database/db');const logger=require('../core/logger');const {QueueManager}=require('./music-queue');
const AsyncMutex=require('./async-mutex');
class SourceResolver{async search(query){const r=await play.search(query,{limit:1});if(!r[0])throw new Error('No music result found.');return{title:r[0].title,url:r[0].url,duration:r[0].durationInSec||0,author:r[0].channel?.name||r[0].author?.name||''}}async stream(track,seek=0){return play.stream(track.url,{quality:2,discordPlayerCompatibility:true,seek:Math.max(0,seek)})}}
class GuildPlayer{
 constructor(guild,manager){this.guild=guild;this.manager=manager;this.queueManager=new QueueManager();this.history=[];this.current=null;this.loop='off';this.volume=80;this.twentyFour=false;this.autoplay=false;this.connection=null;this.player=createAudioPlayer();this.playing=false;this.position=0;this.busy=new AsyncMutex();this.closed=false;this.loadConfig();this.loadState();this.player.on(AudioPlayerStatus.Idle,()=>{if(this.closed)return;return this.advance().catch(error=>logger.error({err:error,guild:guild.id},'music idle recovery failed'));});this.player.on('error',error=>{if(this.closed)return;this.playing=false;logger.error({err:error,guild:guild.id},'music player error');this.advance(true).catch(e=>logger.error({err:e,guild:guild.id},'music error recovery failed'))})}
 loadConfig(){const r=db.prepare('SELECT * FROM music_config WHERE guild_id=?').get(this.guild.id);if(r){this.volume=r.volume;this.loop=r.loop_mode;this.twentyFour=!!r.twenty_four;this.autoplay=!!r.autoplay}}
 loadState(){const q=db.prepare('SELECT track_json FROM music_queue WHERE guild_id=? ORDER BY position').all(this.guild.id);for(const row of q){try{this.queueManager.add(JSON.parse(row.track_json))}catch(error){logger.warn({err:error,guild:this.guild.id},'invalid persisted music queue item ignored')}}const h=db.prepare('SELECT track_json FROM music_history WHERE guild_id=? ORDER BY position').all(this.guild.id);this.history=h.flatMap(r=>{try{return[JSON.parse(r.track_json)]}catch{return[]}}).slice(-50)}
 persistQueue(){const tx=db.transaction(()=>{db.prepare('DELETE FROM music_queue WHERE guild_id=?').run(this.guild.id);const stmt=db.prepare('INSERT INTO music_queue(guild_id,position,track_json) VALUES(?,?,?)');this.queueManager.items.forEach((t,i)=>stmt.run(this.guild.id,i,JSON.stringify(t))) });tx()}
 persistHistory(){const tx=db.transaction(()=>{db.prepare('DELETE FROM music_history WHERE guild_id=?').run(this.guild.id);const stmt=db.prepare('INSERT INTO music_history(guild_id,position,track_json,created_at) VALUES(?,?,?,?)');this.history.slice(-50).forEach((t,i)=>stmt.run(this.guild.id,i,JSON.stringify(t),Date.now()))});tx()}
 saveConfig(){db.prepare('INSERT INTO music_config(guild_id,volume,loop_mode,twenty_four,autoplay,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET volume=excluded.volume,loop_mode=excluded.loop_mode,twenty_four=excluded.twenty_four,autoplay=excluded.autoplay,updated_at=excluded.updated_at').run(this.guild.id,this.volume,this.loop,this.twentyFour?1:0,this.autoplay?1:0,Date.now())}
 async connect(channel){if(this.closed)throw new Error('Music player is shutting down.');if(!channel)throw new Error('Join a voice channel first.');if(this.connection?.state?.status===VoiceConnectionStatus.Destroyed)this.connection=null;if(!this.connection){const connection=joinVoiceChannel({channelId:channel.id,guildId:this.guild.id,adapterCreator:this.guild.voiceAdapterCreator,selfDeaf:true});this.connection=connection;connection.subscribe(this.player);connection.on(VoiceConnectionStatus.Disconnected,async()=>{if(this.connection!==connection)return;try{await Promise.race([connection.rejoin(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('voice reconnect timeout')),5000))]);if(this.connection===connection)logger.info({guild:this.guild.id},'voice connection rejoined')}catch(error){logger.warn({err:error,guild:this.guild.id},'voice reconnect failed');if(this.connection===connection){connection.destroy();this.connection=null}}})}else if(this.connection.joinConfig.channelId!==channel.id)throw new Error('Join the same voice channel as DYNEX.')}
 async playTrack(track,channel){return this.busy.run(async()=>{await this.connect(channel);this.queueManager.add(track);this.persistQueue();if(!this.playing)await this._advance();return this})}
 async _advance(retry=false){if(this.closed)return;if(this.playing&&!retry)return;if(this.loop==='queue'&&this.current&&!retry){this.queueManager.add(this.current);this.persistQueue()}let track=retry&&this.current?this.current:(this.loop==='track'&&this.current?this.current:this.queueManager.next());if(track)this.persistQueue();if(!track&&this.autoplay&&this.current){try{track=await this.manager.resolver.search(`${this.current.title} ${this.current.author||''}`)}catch(error){logger.warn({err:error,guild:this.guild.id},'autoplay lookup failed')}}if(!track){this.current=null;this.playing=false;if(!this.twentyFour){this.connection?.destroy();this.connection=null}return}this.current=track;this.history.push(track);this.history=this.history.slice(-50);this.persistHistory();for(let attempt=0;attempt<3;attempt++){try{const stream=await this.manager.resolver.stream(track,this.position);const resource=createAudioResource(stream.stream,{inputType:stream.type,inlineVolume:true});resource.volume?.setVolume(this.volume/100);this.player.play(resource);this.playing=true;this.position=0;return}catch(error){logger.warn({err:error,guild:this.guild.id,attempt:attempt+1},'music source retry')}}this.playing=false;this.current=null;return this._advance()}
 async advance(retry=false){return this.busy.run(()=>this._advance(retry))}
 async skip(){return this.busy.run(async()=>{if(!this.current)throw new Error('Nothing is playing.');this.position=0;this.player.stop(true);return this.current})}
 async previous(){return this.busy.run(async()=>{if(this.history.length<2)throw new Error('No previous track.');const p=this.history[this.history.length-2];this.queueManager.items.unshift(p);this.persistQueue();this.position=0;this.player.stop(true);return p})}
 pause(){if(!this.playing)throw new Error('Nothing is playing.');this.player.pause()}
 resume(){if(!this.player.unpause())throw new Error('Music is not paused.')}
 stop(){this.queueManager.clear();this.persistQueue();this.current=null;this.playing=false;this.position=0;this.player.stop(true);this.connection?.destroy();this.connection=null}
shutdown(){this.closed=true;this.persistQueue();this.saveConfig();this.persistHistory();this.playing=false;this.player.stop(true);this.connection?.destroy();this.connection=null}
 remove(i){const x=this.queueManager.remove(i);this.persistQueue();return x}clear(){this.queueManager.clear();this.persistQueue()}shuffle(){this.queueManager.shuffle();this.persistQueue()}setVolume(v){this.volume=Math.min(100,Math.max(1,v));this.saveConfig();const r=this.player.state?.resource;if(r?.volume)r.volume.setVolume(this.volume/100)}setLoop(v){if(!['off','track','queue'].includes(v))throw new Error('Invalid loop mode.');this.loop=v;this.saveConfig()}set247(v){this.twentyFour=!!v;this.saveConfig()}setAutoplay(v){this.autoplay=!!v;this.saveConfig()}async seek(seconds){return this.busy.run(async()=>{if(!this.current)throw new Error('Nothing is playing.');this.position=Math.max(0,Math.floor(seconds));this.playing=false;this.player.stop(true);await this._advance(true)})}state(){return{queue:this.queueManager.items,current:this.current,history:this.history,loop:this.loop,volume:this.volume,twentyFour:this.twentyFour,autoplay:this.autoplay,connection:this.connection,player:this.player,playing:this.playing,position:this.position}}}
class MusicManager{constructor(){this.players=new Map();this.resolver=new SourceResolver()}get(guild){let p=this.players.get(guild.id);if(!p){p=new GuildPlayer(guild,this);this.players.set(guild.id,p)}return p}peek(guildId){return this.players.get(typeof guildId==='string'?guildId:guildId?.id)}state(g,create=true){const p=create?this.get(g):this.peek(g);return p?p.state():{queue:[],current:null,history:[],loop:'off',volume:80,twentyFour:false,autoplay:false,connection:null,player:null,playing:false,position:0}}async resolve(q){return this.resolver.search(q)}async playTrack(member,track){return this.get(member.guild).playTrack(track,member.voice.channel)}destroy(guildId,{preserveState=false}={}){const p=this.players.get(guildId);if(p){if(preserveState)p.shutdown();else p.stop();this.players.delete(guildId)}}destroyAll(){for(const id of [...this.players.keys()])this.destroy(id,{preserveState:true})}}
function assertVoiceControl(interaction,player=manager.get(interaction.guild)){const voice=interaction.member?.voice?.channel;if(!voice)throw new Error('Join a voice channel first.');if(player.connection&&player.connection.joinConfig.channelId!==voice.id)throw new Error('You must be in the same voice channel as DYNEX.');return player}
const manager=new MusicManager();module.exports={MusicManager,GuildPlayer,QueueManager,SourceResolver,manager,players:manager.players,assertVoiceControl,state:(...a)=>manager.state(...a),resolve:(...a)=>manager.resolve(...a),playTrack:(...a)=>manager.playTrack(...a)};
