const crypto=require('crypto');
const {PermissionFlagsBits,AuditLogEvent}=require('discord.js');
const {db}=require('../database/db');
const TTLCache=require('../cache/ttl');
const logger=require('../core/logger');
const engine=require('./security-engine');const policy=require('./security-policy');
const recovery=require('./recovery');
const joins=new TTLCache(10000),leaves=new TTLCache(10000),names=new TTLCache(10000),actions=new TTLCache(20000);
const ACTION_DEFAULTS={
 [AuditLogEvent.ChannelDelete]:{threshold:3,windowMs:15000},[AuditLogEvent.ChannelCreate]:{threshold:5,windowMs:15000},
 [AuditLogEvent.RoleDelete]:{threshold:3,windowMs:15000},[AuditLogEvent.RoleCreate]:{threshold:5,windowMs:15000},
 [AuditLogEvent.ChannelOverwriteCreate]:{threshold:5,windowMs:15000},[AuditLogEvent.ChannelOverwriteUpdate]:{threshold:5,windowMs:15000},
 [AuditLogEvent.ChannelOverwriteDelete]:{threshold:5,windowMs:15000},[AuditLogEvent.WebhookCreate]:{threshold:3,windowMs:15000},
 [AuditLogEvent.WebhookDelete]:{threshold:3,windowMs:15000},[AuditLogEvent.BotAdd]:{threshold:2,windowMs:30000},
 [AuditLogEvent.MemberBanAdd]:{threshold:5,windowMs:15000},[AuditLogEvent.MemberKick]:{threshold:5,windowMs:15000},
 [AuditLogEvent.MemberRoleUpdate]:{threshold:3,windowMs:15000},[AuditLogEvent.GuildUpdate]:{threshold:2,windowMs:30000}
};
function record(guildId,actorId,eventType,details=''){return Number(db.prepare('INSERT INTO security_events(guild_id,actor_id,event_type,details,created_at) VALUES(?,?,?,?,?)').run(guildId,actorId||null,eventType,details,Date.now()).lastInsertRowid)}
function incidentId(){return`INC-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`}
function createIncident(guildId,actorId,eventType,evidence,action){const id=incidentId();db.prepare('INSERT INTO security_incidents(incident_id,guild_id,actor_id,event_type,evidence_json,action,created_at) VALUES(?,?,?,?,?,?,?)').run(id,guildId,actorId||null,eventType,JSON.stringify(evidence||{}),action,Date.now());record(guildId,actorId,`incident:${eventType}`,`${id} ${action}`);return id}
function recoverIncident(id){db.prepare('UPDATE security_incidents SET recovered_at=? WHERE incident_id=? AND recovered_at IS NULL').run(Date.now(),id)}
function getThreshold(guildId,eventType){const r=db.prepare('SELECT threshold,window_ms FROM security_thresholds WHERE guild_id=? AND event_type=?').get(guildId,String(eventType));return r||ACTION_DEFAULTS[eventType]||{threshold:3,windowMs:15000}}
function setThreshold(guildId,eventType,threshold,windowMs){if(!Number.isInteger(threshold)||threshold<1||threshold>100||!Number.isInteger(windowMs)||windowMs<1000||windowMs>300000)throw new Error('Invalid security threshold.');db.prepare('INSERT INTO security_thresholds(guild_id,event_type,threshold,window_ms) VALUES(?,?,?,?) ON CONFLICT(guild_id,event_type) DO UPDATE SET threshold=excluded.threshold,window_ms=excluded.window_ms').run(guildId,String(eventType),threshold,windowMs)}
function isWhitelisted(guild,member){if(!member)return false;if(member.id===guild.ownerId)return true;if(db.prepare('SELECT 1 FROM security_whitelist WHERE guild_id=? AND kind=? AND user_id=? LIMIT 1').get(guild.id,'user',member.id))return true;return db.prepare('SELECT role_id FROM security_whitelist WHERE guild_id=? AND kind=? AND role_id IS NOT NULL').all(guild.id,'role').some(x=>member.roles.cache.has(x.role_id))}
function join(guild,member){const now=Date.now(),s=db.prepare('SELECT * FROM guild_settings WHERE guild_id=?').get(guild.id)||{},threshold=Number(s.antiraid_join_threshold)||20,windowMs=Number(s.antiraid_window_ms)||15000,namesNow=(names.get(guild.id)||[]).filter(x=>now-x.time<30000),arr=(joins.get(guild.id)||[]).filter(t=>now-t<windowMs);arr.push(now);joins.set(guild.id,arr,windowMs+1000);const similar=namesNow.some(x=>engine.similarity(x.name,member.user.username)>=(s.antiraid_similarity_threshold??0.85));namesNow.push({name:member.user.username,time:now});names.set(guild.id,namesNow.slice(-100),31000);const ageDays=Math.max(0,Math.floor((now-member.user.createdTimestamp)/86400000));const leaveBurst=(leaves.get(guild.id)||[]).filter(t=>now-t<windowMs).length;const risk=policy.classifyRisk({accountAgeDays:ageDays,similar,velocity:arr.length,threshold,joinLeaveBurst:leaveBurst});return{raid:arr.length>=threshold||risk.critical,suspicious:ageDays<(s.antiraid_min_account_age_days??7)||similar||risk.suspicious,critical:risk.critical,riskScore:risk.score,velocity:arr.length,similar,accountAgeDays:ageDays,joinLeaveBurst:leaveBurst,threshold,windowMs}}
async function quarantine(guild,userId,roleId){const m=await guild.members.fetch(userId),me=guild.members.me;if(!m||!me?.permissions.has(PermissionFlagsBits.ManageRoles)||m.id===guild.ownerId||m.id===me.id||m.roles.highest.position>=me.roles.highest.position)return false;const role=roleId&&guild.roles.cache.get(roleId);if(role&&role.position<me.roles.highest.position)await m.roles.set([role],'DYNEX security quarantine');else await m.roles.set([],'DYNEX security quarantine');return true}
function markAction(key,windowMs){const now=Date.now(),arr=(actions.get(key)||[]).filter(t=>now-t<windowMs);arr.push(now);actions.set(key,arr,windowMs+1000);return arr.length}
async function detectAuditExecutor(guild,entry){if(!entry?.executorId||entry.executorId===guild.ownerId)return null;const m=await guild.members.fetch(entry.executorId).catch(error=>{logger.warn({err:error,executor:entry.executorId},'audit executor fetch failed');return null});if(!m||m.user?.bot||isWhitelisted(guild,m))return null;const t=getThreshold(guild.id,entry.action),w=Number(t.windowMs??t.window_ms)||15000,c=markAction(`${guild.id}:${entry.executorId}:${entry.action}`,w);return{member:m,count:c,threshold:t.threshold,windowMs:w}}
async function lockdown(guild){const me=guild.members.me;if(!me?.permissions.has(PermissionFlagsBits.ManageChannels))throw new Error('I need Manage Channels for lockdown.');const everyone=guild.roles.everyone;for(const channel of guild.channels.cache.values()){if(!channel.isTextBased()||!channel.permissionOverwrites?.edit)continue;const current=channel.permissionsFor(everyone);if(current?.has(PermissionFlagsBits.SendMessages)){const existingOverwrite=channel.permissionOverwrites.cache.get(everyone.id);const hadExplicitAllow=existingOverwrite?.allow?.has(PermissionFlagsBits.SendMessages)?1:0;await channel.permissionOverwrites.edit(everyone,{SendMessages:false},'DYNEX security lockdown');db.prepare('INSERT OR REPLACE INTO security_lockdown_channels(guild_id,channel_id,created_at,had_explicit_allow) VALUES(?,?,?,?)').run(guild.id,channel.id,Date.now(),hadExplicitAllow)}}record(guild.id,guild.client.user?.id,'lockdown','tracked text channels locked')}
async function unlock(guild){const me=guild.members.me;if(!me?.permissions.has(PermissionFlagsBits.ManageChannels))throw new Error('I need Manage Channels to unlock.');const rows=db.prepare('SELECT channel_id,had_explicit_allow FROM security_lockdown_channels WHERE guild_id=?').all(guild.id);for(const row of rows){const channel=guild.channels.cache.get(row.channel_id);if(channel?.permissionOverwrites?.edit)await channel.permissionOverwrites.edit(guild.roles.everyone,{SendMessages:row.had_explicit_allow?true:null},'DYNEX security unlock')}db.prepare('DELETE FROM security_lockdown_channels WHERE guild_id=?').run(guild.id);record(guild.id,guild.client.user?.id,'unlock','security lockdown released')}
function setRaid(guildId,enabled,until=0,incident=null){db.prepare('INSERT INTO security_state(guild_id,raid_mode,raid_until,incident_id,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET raid_mode=excluded.raid_mode,raid_until=excluded.raid_until,incident_id=excluded.incident_id,updated_at=excluded.updated_at').run(guildId,enabled?1:0,until,enabled?(incident||null):null,Date.now());if(incident&&!enabled)recoverIncident(incident)}
function getRaid(guildId){return db.prepare('SELECT * FROM security_state WHERE guild_id=?').get(guildId)||{raid_mode:0,raid_until:0}}
async function leave(guild){const now=Date.now();const arr=(leaves.get(guild.id)||[]).filter(t=>now-t<30000);arr.push(now);leaves.set(guild.id,arr,31000);return arr.length}
async function recoverExpiredRaid(guild){const r=getRaid(guild.id);if(!r.raid_mode||!r.raid_until||r.raid_until>Date.now())return false;const incident=r.incident_id||null;setRaid(guild.id,false,0);if(incident)recoverIncident(incident);try{await unlock(guild)}catch(error){logger.warn({err:error,guild:guild.id},'raid lockdown recovery failed')}record(guild.id,guild.client.user?.id,'raid-recovered','automatic raid mode recovery');return true}
async function restoreTarget(guild,targetId,incident){const result=await recovery.restore(guild,targetId);record(guild.id,incident?'system':null,'security-recovery',`incident=${incident||'n/a'} target=${targetId} restored=${result.restored} reason=${result.reason||'ok'}`);return result}
function listIncidents(guildId,limit=10){return db.prepare('SELECT * FROM security_incidents WHERE guild_id=? ORDER BY id DESC LIMIT ?').all(guildId,Math.min(Math.max(limit,1),50))}
function recentEvents(guildId,limit=15){return db.prepare('SELECT * FROM security_events WHERE guild_id=? ORDER BY id DESC LIMIT ?').all(guildId,Math.min(Math.max(limit,1),50))}
function addWhitelist(guildId,kind,id){if(!['user','role'].includes(kind)||!/^\d{17,20}$/.test(id))throw new Error('Invalid whitelist target.');db.prepare('INSERT OR IGNORE INTO security_whitelist(guild_id,user_id,role_id,kind) VALUES(?,?,?,?)').run(guildId,kind==='user'?id:null,kind==='role'?id:null,kind)}
function removeWhitelist(guildId,kind,id){db.prepare('DELETE FROM security_whitelist WHERE guild_id=? AND kind=? AND (user_id=? OR role_id=?)').run(guildId,kind,id,id)}
module.exports={ACTION_DEFAULTS,lockdown,unlock,similarity:engine.similarity,record,createIncident,recoverIncident,getThreshold,setThreshold,isWhitelisted,join,leave,quarantine,markAction,detectAuditExecutor,setRaid,getRaid,recoverExpiredRaid,restoreTarget,listIncidents,recentEvents,addWhitelist,removeWhitelist};
