const {SlashCommandBuilder,PermissionFlagsBits}=require('discord.js');const {mw}=require('./_helpers');const automod=require('../services/automod');
const types=s=>s.addStringOption(o=>o.setName('type').setDescription('Rule type').setRequired(true).addChoices({name:'Keyword',value:'keyword'},{name:'Regex',value:'regex'},{name:'Spam',value:'spam'},{name:'Mention spam',value:'mention_spam'},{name:'Preset',value:'preset'})).addStringOption(o=>o.setName('value').setDescription('Keywords, regex patterns, or mention limit').setRequired(false));
const command=new SlashCommandBuilder().setName('automod').setDescription('Manage native Discord AutoMod').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
.addSubcommand(s=>s.setName('setup').setDescription('Create a keyword rule').addStringOption(o=>o.setName('keywords').setDescription('Comma-separated keywords').setRequired(true)))
.addSubcommand(s=>s.setName('status').setDescription('Show AutoMod status')).addSubcommand(s=>s.setName('rules').setDescription('List AutoMod rules'))
.addSubcommandGroup(g=>g.setName('rule').setDescription('Manage rules').addSubcommand(s=>types(s.setName('add').setDescription('Add a rule'))).addSubcommand(s=>s.setName('edit').setDescription('Edit a rule').addStringOption(o=>o.setName('id').setDescription('Rule ID').setRequired(true)).addStringOption(o=>o.setName('type').setDescription('Rule type').setRequired(true).addChoices({name:'Keyword',value:'keyword'},{name:'Regex',value:'regex'},{name:'Spam',value:'spam'},{name:'Mention spam',value:'mention_spam'})).addStringOption(o=>o.setName('value').setDescription('Keywords, patterns, or mention limit').setRequired(false))).addSubcommand(s=>s.setName('delete').setDescription('Delete a rule').addStringOption(o=>o.setName('id').setDescription('Rule ID').setRequired(true))))
.addSubcommand(s=>s.setName('exempt-role').setDescription('Exempt a role').addStringOption(o=>o.setName('id').setDescription('Rule ID').setRequired(true)).addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)))
.addSubcommand(s=>s.setName('exempt-channel').setDescription('Exempt a channel').addStringOption(o=>o.setName('id').setDescription('Rule ID').setRequired(true)).addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true)))
.addSubcommand(s=>s.setName('logs').setDescription('View AutoMod action logs'));
async function execute(i){const sub=i.options.getSubcommand();if(sub==='setup'){const words=i.options.getString('keywords').split(',').map(x=>x.trim()).filter(Boolean);const r=await automod.create(i.guild,{name:'DYNEX Keyword Guard',type:'keyword',keywords:words});return i.reply(`🛡️ Created **${r.name}** (${r.id})`)}if(sub==='status'||sub==='rules'){const rows=automod.list(i.guild.id);return i.reply(rows.length?rows.map(r=>`• **${r.name}** — \`${r.rule_id}\` — ${r.enabled?'ON':'OFF'}`).join('\n'):'No DYNEX-managed AutoMod rules.')}if(i.options.getSubcommandGroup()==='rule'){const action=i.options.getSubcommand();if(action==='delete'){await automod.remove(i.guild,i.options.getString('id'));return i.reply('🗑️ AutoMod rule deleted.')}const type=i.options.getString('type');const value=i.options.getString('value')||'';const input={name:`DYNEX ${type}`,type};if(type==='keyword')input.keywords=value.split(',').map(x=>x.trim()).filter(Boolean);if(type==='regex')input.patterns=value.split(',').map(x=>x.trim()).filter(Boolean);if(type==='mention_spam')input.mentionLimit=Number(value)||5;if(action==='edit')input.name=`DYNEX ${type}`;const r=action==='add'?await automod.create(i.guild,input):await automod.edit(i.guild,i.options.getString('id'),input);return i.reply(`🛡️ ${action==='add'?'Created':'Updated'} **${r.name}** (${r.id})`)}if(sub==='exempt-role'){await automod.exempt(i.guild,i.options.getString('id'),{roleId:i.options.getRole('role').id});return i.reply('✅ Role exemption saved.')}if(sub==='exempt-channel'){await automod.exempt(i.guild,i.options.getString('id'),{channelId:i.options.getChannel('channel').id});return i.reply('✅ Channel exemption saved.')}const rows=automod.logs(i.guild.id);return i.reply(rows.length?rows.map(x=>`#${x.id} • rule=${x.rule_id||'n/a'} • user=<@${x.user_id}> • ${x.action_type||'action'}`).join('\n'):'No AutoMod actions logged.')}
module.exports={data:command,execute};
