const {AuditLogEvent,PermissionFlagsBits}=require('discord.js');
const {db}=require('../database/db');
const repo=require('../repositories/guild');
const security=require('../services/security');
const logger=require('../core/logger');
const destructive=new Set([
 AuditLogEvent.ChannelDelete,AuditLogEvent.ChannelCreate,AuditLogEvent.RoleDelete,AuditLogEvent.RoleCreate,
 AuditLogEvent.ChannelOverwriteCreate,AuditLogEvent.ChannelOverwriteUpdate,AuditLogEvent.ChannelOverwriteDelete,
 AuditLogEvent.WebhookCreate,AuditLogEvent.WebhookDelete,AuditLogEvent.BotAdd,AuditLogEvent.MemberBanAdd,
 AuditLogEvent.MemberKick,AuditLogEvent.MemberRoleUpdate,AuditLogEvent.GuildUpdate
]);
async function alert(guild,incident,entry,hit){const s=repo.get(guild.id);const ch=s?.mod_log_channel_id&&guild.channels.cache.get(s.mod_log_channel_id);if(!ch?.isTextBased())return;await ch.send(`🚨 DYNEX SECURITY **${incident}**\nAction: ${entry.action}\nExecutor: <@${entry.executorId}>\nThreshold: ${hit.count}/${hit.threshold}`).catch(error=>logger.warn({err:error,guild:guild.id,incident},'security alert send failed'))}
module.exports={name:'guildAuditLogEntryCreate',async execute(entry,guild){if(!destructive.has(entry.action))return;const s=repo.get(guild.id);if(!s?.antinuke_enabled||!entry.executorId)return;const hit=await security.detectAuditExecutor(guild,entry);if(!hit)return;security.record(guild.id,entry.executorId,`audit:${entry.action}`,`count=${hit.count}/${hit.threshold};target=${entry.targetId||'n/a'}`);if(hit.count<hit.threshold)return;const incident=security.createIncident(guild.id,entry.executorId,String(entry.action),{count:hit.count,threshold:hit.threshold,targetId:entry.targetId||null},'protect');await alert(guild,incident,entry,hit);try{await security.quarantine(guild,entry.executorId,s.unverified_role_id)}catch(error){logger.error({err:error,guild:guild.id,incident},'anti-nuke quarantine failed')}
if(entry.action===AuditLogEvent.BotAdd&&entry.targetId){try{const added=guild.members.cache.get(entry.targetId)||await guild.members.fetch(entry.targetId);if(added&&added.user.bot&&added.id!==guild.ownerId&&guild.members.me?.permissions.has(PermissionFlagsBits.KickMembers)&&added.roles.highest.position<guild.members.me.roles.highest.position)await added.kick(`DYNEX security incident ${incident}`)}catch(error){logger.warn({err:error,guild:guild.id,incident},'added bot containment failed')}}if([AuditLogEvent.ChannelDelete,AuditLogEvent.RoleDelete].includes(entry.action)&&entry.targetId){const result=await security.restoreTarget(guild,entry.targetId,incident);security.record(guild.id,entry.executorId,'recovery-result',`incident=${incident};restored=${result.restored};reason=${result.reason||'ok'}`)}if([AuditLogEvent.ChannelDelete,AuditLogEvent.RoleDelete,AuditLogEvent.ChannelOverwriteUpdate,AuditLogEvent.MemberRoleUpdate,AuditLogEvent.GuildUpdate].includes(entry.action)){try{if(!security.getRaid(guild.id).raid_mode){security.setRaid(guild.id,true,Date.now()+120000,incident);await security.lockdown(guild)}}catch(error){logger.warn({err:error,guild:guild.id,incident},'security containment failed')}}if(!guild.members.me?.permissions.has(PermissionFlagsBits.ManageRoles))logger.warn({guild:guild.id,incident},'bot lacks Manage Roles for full quarantine')}};
