CREATE TABLE IF NOT EXISTS guilds (id text PRIMARY KEY,name text NOT NULL,icon text,locale text NOT NULL DEFAULT 'en-US',automod_enabled boolean NOT NULL DEFAULT true,security_enabled boolean NOT NULL DEFAULT true,leveling_enabled boolean NOT NULL DEFAULT true,economy_enabled boolean NOT NULL DEFAULT true,tickets_enabled boolean NOT NULL DEFAULT true,starboard_enabled boolean NOT NULL DEFAULT false,starboard_threshold integer NOT NULL DEFAULT 3,log_channel_id text,mod_log_channel_id text,welcome_channel_id text,welcome_message text,ai_enabled boolean NOT NULL DEFAULT false,ai_channel_id text,ai_system_prompt text);
CREATE TABLE IF NOT EXISTS cases (id text PRIMARY KEY,guild_id text NOT NULL REFERENCES guilds(id),type text NOT NULL,target_id text NOT NULL,actor_id text NOT NULL,reason text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS cases_guild_idx ON cases(guild_id);
CREATE TABLE IF NOT EXISTS warnings (id text PRIMARY KEY,guild_id text NOT NULL,user_id text NOT NULL,actor_id text NOT NULL,reason text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS xp (guild_id text NOT NULL,user_id text NOT NULL,xp integer NOT NULL DEFAULT 0,level integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT xp_member_idx UNIQUE(guild_id,user_id));
CREATE INDEX IF NOT EXISTS xp_guild_idx ON xp(guild_id,xp);
CREATE TABLE IF NOT EXISTS balances (guild_id text NOT NULL,user_id text NOT NULL,balance integer NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT balance_member_idx UNIQUE(guild_id,user_id));
CREATE TABLE IF NOT EXISTS audit (id text PRIMARY KEY,guild_id text NOT NULL,actor_id text NOT NULL,action text NOT NULL,target_id text,before jsonb,after jsonb,metadata jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS config (guild_id text NOT NULL,key text NOT NULL,value jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT config_key_idx UNIQUE(guild_id,key));
