import { pgTable, text, integer, boolean, timestamp, jsonb, index, uniqueIndex, primaryKey } from 'drizzle-orm/pg-core';

export const guilds = pgTable('guilds', {
  id:text('id').primaryKey(), name:text('name').notNull(), icon:text('icon'), locale:text('locale').notNull().default('en-US'),
  automodEnabled:boolean('automod_enabled').notNull().default(true), securityEnabled:boolean('security_enabled').notNull().default(true),
  levelingEnabled:boolean('leveling_enabled').notNull().default(true), economyEnabled:boolean('economy_enabled').notNull().default(true), ticketsEnabled:boolean('tickets_enabled').notNull().default(true),
  starboardEnabled:boolean('starboard_enabled').notNull().default(false), starboardThreshold:integer('starboard_threshold').notNull().default(3),
  logChannelId:text('log_channel_id'), modLogChannelId:text('mod_log_channel_id'), welcomeChannelId:text('welcome_channel_id'), goodbyeChannelId:text('goodbye_channel_id'),
  welcomeMessage:text('welcome_message'), goodbyeMessage:text('goodbye_message'), aiEnabled:boolean('ai_enabled').notNull().default(false), aiChannelId:text('ai_channel_id'), aiSystemPrompt:text('ai_system_prompt'),
  securityThresholds:jsonb('security_thresholds'), updatedAt:timestamp('updated_at').notNull().defaultNow()
});
export const cases = pgTable('cases',{id:text('id').primaryKey(),guildId:text('guild_id').notNull().references(()=>guilds.id),type:text('type').notNull(),targetId:text('target_id').notNull(),actorId:text('actor_id').notNull(),reason:text('reason'),metadata:jsonb('metadata'),createdAt:timestamp('created_at').notNull().defaultNow()},{caseGuildIdx:index('cases_guild_idx').on('guildId','createdAt')});
export const warnings = pgTable('warnings',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),userId:text('user_id').notNull(),actorId:text('actor_id').notNull(),reason:text('reason'),active:boolean('active').notNull().default(true),createdAt:timestamp('created_at').notNull().defaultNow()},{warnIdx:index('warnings_user_idx').on('guildId','userId','createdAt')});
export const xp = pgTable('xp',{guildId:text('guild_id').notNull(),userId:text('user_id').notNull(),xp:integer('xp').notNull().default(0),level:integer('level').notNull().default(1),messages:integer('messages').notNull().default(0),updatedAt:timestamp('updated_at').notNull().defaultNow()},{idx:uniqueIndex('xp_member_idx').on('guildId','userId'),xpGuildIdx:index('xp_guild_idx').on('guildId','xp')});
export const xpRewards = pgTable('xp_rewards',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),level:integer('level').notNull(),roleId:text('role_id'),message:text('message')},{idx:uniqueIndex('xp_reward_unique').on('guildId','level')});
export const balances = pgTable('balances',{guildId:text('guild_id').notNull(),userId:text('user_id').notNull(),balance:integer('balance').notNull().default(0),updatedAt:timestamp('updated_at').notNull().defaultNow()},{idx:uniqueIndex('balance_member_idx').on('guildId','userId')});
export const economyTransactions = pgTable('economy_transactions',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),userId:text('user_id').notNull(),amount:integer('amount').notNull(),type:text('type').notNull(),metadata:jsonb('metadata'),createdAt:timestamp('created_at').notNull().defaultNow()},{idx:index('economy_tx_idx').on('guildId','userId','createdAt')});
export const economyItems = pgTable('economy_items',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),name:text('name').notNull(),description:text('description'),price:integer('price').notNull(),stock:integer('stock').notNull().default(-1),metadata:jsonb('metadata')});
export const economyInventory = pgTable('economy_inventory',{guildId:text('guild_id').notNull(),userId:text('user_id').notNull(),itemId:text('item_id').notNull(),quantity:integer('quantity').notNull().default(0)},{pk:primaryKey({columns:[text('guild_id'),text('user_id'),text('item_id')] as any})});
export const cooldowns = pgTable('cooldowns',{guildId:text('guild_id').notNull(),userId:text('user_id').notNull(),key:text('key').notNull(),expiresAt:timestamp('expires_at').notNull()},{idx:uniqueIndex('cooldown_unique').on('guildId','userId','key')});
export const audit = pgTable('audit',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),actorId:text('actor_id').notNull(),action:text('action').notNull(),targetId:text('target_id'),before:jsonb('before'),after:jsonb('after'),metadata:jsonb('metadata'),createdAt:timestamp('created_at').notNull().defaultNow()},{idx:index('audit_guild_idx').on('guildId','createdAt')});
export const config = pgTable('config',{guildId:text('guild_id').notNull(),key:text('key').notNull(),value:jsonb('value').notNull(),updatedAt:timestamp('updated_at').notNull().defaultNow()},{pk:uniqueIndex('config_key_idx').on('guildId','key')});
export const securityTrusted = pgTable('security_trusted',{guildId:text('guild_id').notNull(),subjectId:text('subject_id').notNull(),kind:text('kind').notNull()},{pk:primaryKey({columns:[text('guild_id'),text('subject_id'),text('kind')] as any})});
export const securityEvents = pgTable('security_events',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),type:text('type').notNull(),actorId:text('actor_id'),targetId:text('target_id'),severity:text('severity').notNull(),metadata:jsonb('metadata'),createdAt:timestamp('created_at').notNull().defaultNow()},{idx:index('security_event_idx').on('guildId','createdAt')});
export const tickets = pgTable('tickets',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),userId:text('user_id').notNull(),panelId:text('panel_id'),categoryId:text('category_id'),claimedBy:text('claimed_by'),status:text('status').notNull().default('open'),subject:text('subject'),createdAt:timestamp('created_at').notNull().defaultNow(),closedAt:timestamp('closed_at')},{idx:index('tickets_guild_idx').on('guildId','status')});
export const ticketPanels = pgTable('ticket_panels',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),messageId:text('message_id').notNull(),categoryId:text('category_id'),staffRoleId:text('staff_role_id'),title:text('title').notNull(),description:text('description'),form:jsonb('form'),createdAt:timestamp('created_at').notNull().defaultNow()},{idx:index('ticket_panel_guild_idx').on('guildId')});
export const transcripts = pgTable('transcripts',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),ticketId:text('ticket_id').notNull(),content:text('content').notNull(),createdAt:timestamp('created_at').notNull().defaultNow()});
export const giveaways = pgTable('giveaways',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),messageId:text('message_id'),prize:text('prize').notNull(),winnerCount:integer('winner_count').notNull(),endsAt:timestamp('ends_at').notNull(),requirements:jsonb('requirements'),status:text('status').notNull().default('running'),winners:jsonb('winners'),createdAt:timestamp('created_at').notNull().defaultNow()},{idx:index('giveaway_guild_idx').on('guildId','status')});
export const giveawayEntries = pgTable('giveaway_entries',{giveawayId:text('giveaway_id').notNull(),userId:text('user_id').notNull(),enteredAt:timestamp('entered_at').notNull().defaultNow()},{pk:primaryKey({columns:[text('giveaway_id'),text('user_id')] as any})});
export const rolePanels = pgTable('role_panels',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),messageId:text('message_id').notNull(),title:text('title').notNull(),exclusive:boolean('exclusive').notNull().default(false),roles:jsonb('roles').notNull(),createdAt:timestamp('created_at').notNull().defaultNow()});
export const autoroles = pgTable('autoroles',{guildId:text('guild_id').notNull(),roleId:text('role_id').notNull(),type:text('type').notNull()},{pk:primaryKey({columns:[text('guild_id'),text('role_id'),text('type')] as any})});
export const starboard = pgTable('starboard',{guildId:text('guild_id').notNull(),messageId:text('message_id').notNull(),channelId:text('channel_id').notNull(),starMessageId:text('star_message_id'),count:integer('count').notNull(),updatedAt:timestamp('updated_at').notNull().defaultNow()},{pk:primaryKey({columns:[text('guild_id'),text('message_id')] as any})});
export const polls = pgTable('polls',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),messageId:text('message_id').notNull(),question:text('question').notNull(),options:jsonb('options').notNull(),endsAt:timestamp('ends_at'),status:text('status').notNull().default('open'),createdAt:timestamp('created_at').notNull().defaultNow()});
export const pollVotes = pgTable('poll_votes',{pollId:text('poll_id').notNull(),userId:text('user_id').notNull(),option:integer('option').notNull(),createdAt:timestamp('created_at').notNull().defaultNow()},{pk:primaryKey({columns:[text('poll_id'),text('user_id')] as any})});
export const suggestions = pgTable('suggestions',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),messageId:text('message_id').notNull(),userId:text('user_id').notNull(),content:text('content').notNull(),status:text('status').notNull().default('pending'),staffResponse:text('staff_response'),createdAt:timestamp('created_at').notNull().defaultNow()});
export const suggestionVotes = pgTable('suggestion_votes',{suggestionId:text('suggestion_id').notNull(),userId:text('user_id').notNull(),value:integer('value').notNull(),createdAt:timestamp('created_at').notNull().defaultNow()},{pk:primaryKey({columns:[text('suggestion_id'),text('user_id')] as any})});
export const events = pgTable('events',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),messageId:text('message_id'),title:text('title').notNull(),description:text('description'),startsAt:timestamp('starts_at').notNull(),timezone:text('timezone').notNull().default('UTC'),status:text('status').notNull().default('scheduled'),createdAt:timestamp('created_at').notNull().defaultNow()});
export const eventRsvps = pgTable('event_rsvps',{eventId:text('event_id').notNull(),userId:text('user_id').notNull(),status:text('status').notNull().default('going'),createdAt:timestamp('created_at').notNull().defaultNow()},{pk:primaryKey({columns:[text('event_id'),text('user_id')] as any})});
export const analytics = pgTable('analytics',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),type:text('type').notNull(),userId:text('user_id'),channelId:text('channel_id'),value:integer('value').notNull().default(1),metadata:jsonb('metadata'),createdAt:timestamp('created_at').notNull().defaultNow()},{idx:index('analytics_guild_idx').on('guildId','type','createdAt')});
export const backups = pgTable('backups',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),actorId:text('actor_id').notNull(),payload:jsonb('payload').notNull(),createdAt:timestamp('created_at').notNull().defaultNow()});
export const translations = pgTable('translations',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),source:text('source').notNull(),target:text('target').notNull(),provider:text('provider').notNull(),createdAt:timestamp('created_at').notNull().defaultNow()});
export const aiMessages = pgTable('ai_messages',{id:text('id').primaryKey(),guildId:text('guild_id').notNull(),channelId:text('channel_id').notNull(),userId:text('user_id').notNull(),role:text('role').notNull(),content:text('content').notNull(),createdAt:timestamp('created_at').notNull().defaultNow()},{idx:index('ai_history_idx').on('guildId','channelId','createdAt')});
